import java.util.HashSet;
import java.util.Set;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and
 * then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 */
public class FindTheDifference
{
    public static char findTheDifference(String s, String t)
    {
        Set<Character> set = new HashSet<>();
        
        char[] tChars = t.toCharArray();
        char[] sChars = s.toCharArray();
        
        for (int i = 0; i < tChars.length; i++)
        {
            if (!set.contains(tChars[i]))
                set.add(tChars[i]);
            else
                set.remove(tChars[i]);
        }
        
        for (int i = 0; i < sChars.length; i++)
        {
            if (!set.contains(sChars[i]))
                set.add(sChars[i]);
            else
                set.remove(sChars[i]);
        }
        
        return (char) set.toArray()[0];
    }
    
    public static void main(String[] args)
    {
        System.out.println(findTheDifference("a", "aa"));
    }
}